name: major_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_auth: ^4.12.0
  firebase_database: ^10.3.2
  cloud_firestore: ^4.12.1
  qr_flutter: ^4.1.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  qrscan: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Teacher.png
    - assets/Student.png