// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHaNJsik4ZM303aufWhXleG0qAlHuQla4',
    appId: '1:52203538370:android:e2d123f47d9f1ffca5f85b',
    messagingSenderId: '52203538370',
    projectId: 'major-app-b274b',
    storageBucket: 'major-app-b274b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA9daMKU6CrnnGvJlgOH6MIBs6PeRba7E',
    appId: '1:52203538370:ios:9b37a9f74197c976a5f85b',
    messagingSenderId: '52203538370',
    projectId: 'major-app-b274b',
    storageBucket: 'major-app-b274b.appspot.com',
    androidClientId: '52203538370-gpb22j2feqg4t7huemt1vc277itpbcde.apps.googleusercontent.com',
    iosClientId: '52203538370-p7m6jb8f98aasu4b956fvjnp851jhk1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.majorApp',
  );
}
